# From: https://github.com/4GeeksAcademy/flask-rest-hello/blob/main/render.yml
services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    region: ohio
    name: flask-template
    env: python # valid values: https://render.com/docs/yaml-spec#environment
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi --chdir ./src/"
    plan: free # optional; defaults to starter
    numInstances: 1
    envVars:
      - key: POSTGRES_URL # Render PostgreSQL database
        fromDatabase:
          name: flask-rest-42170
          property: connectionString

databases: # Render PostgreSQL database
  - name: flask-rest-42170
    region: ohio
    ipAllowList: [] # only allow internal connections
    plan: free # optional; defaults to starter
